identifier: l8d2ebw3y21d3c13
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: nhanth-dev
homeFolder: C:\Users\NhanTrinh\Documents\GitHub Project\nhanth.dev
distFolder: site/nhanth-dev
outDir: C:\Users\NhanTrinh\Documents\GitHub Project\nhanth.dev\site\static
handle404: ''
allowErrorCollect: false
